### ISSUE TITLE
Watchtower is intermittently alerting while systems are being shutdown

### ISSUE THREAD

**Issue by kjenneycloudhealth** [containrrr/watchtower#1034]
**Describe the bug**
I have Watchtower running on 100's of EC2 instances. We have Watchtower configured to alert on errors via Slack (shoutrrr). Occasionally (about 1 in a 100) when instances are being shutdown we will receive a Slack message:

```
NODENAME (error): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

We just upgraded to 1.3.0 and noticed this behavior immediately after upgrading. Nothing else has changed on our systems as far as I can tell that would have caused this. We are running Ubuntu 20.04 and have been for months. We are using the upstream docker-ce package with no modifications.

**To Reproduce**
I'm not able to reproduce the condition manually at the moment I've tried a number of times to initiate a Docker stop when the Watchtower container is in a scheduled run. 

**Expected behavior**
The Watchtower container should stop gracefully without erroring.

**Environment**
* Ubuntu 20.04
* Arch: x86_64
* Docker 20.10.7

**Comment by piksel** [comment]
Could you look at the logs at the time of the error? I'm not entirely sure what state Watchtower is in... especially since it would seem like Docker has been shut down, but Watchtower is still running...?

**Comment by kjenneycloudhealth** [comment]
The issue now is that this is happening when an instance is being shutdown for termination so there's no way to pull the logs. I need to wire up some systems to stream the watchtower logs (with debug) externally so they can be recovered. For now I've downgraded to 1.2.1 and the alerts have stopped.

**Comment by piksel** [comment]
Regarding the `NODENAME (error):` part of the message; is `NODENAME` the actual string or something like the hostname? Do you use a custom template for the notifications?

**Comment by kjenneycloudhealth** [comment]
> Regarding the `NODENAME (error):` part of the message; is `NODENAME` the actual string or something like the hostname? Do you use a custom template for the notifications?

NODENAME is part of a custom shoutrrr template. It is the hostname of the system hosting the container.

**Comment by piksel** [comment]
and `error` is the `.Level` of the message? There could be a couple of places where this can happen, but the reason for it not happening in 1.2.1 is due to a bug that meant that watchtower exited before some error messages could be sent. The error still happens, it just fails to notify about it.

~I think the "cause" of this error is that watchtower doesn't handle graceful shutdowns. If it would stop the scheduler (perhaps even abort any ongoing session, but that would require a bit more work) when `SIGTERM` was received, and then exit, I think this could be avoided.~

Never mind, it does graceful shutdowns exactly as I described above. So yeah, I have no idea what is going on in your environment. Perhaps it doesn't wait for containers to shut down before killing docker? 🤷‍♀️

**Comment by kjenneycloudhealth** [comment]
It is an error level message. I'll dig in more but as far as I know nothing sgould be special about the way that Docker is installed and configured. Some of these systems are under heavy load and we've seen issues where containers hang on Docker stop. This ia probably related to that.

**Comment by simonaronsson** [comment]
This issue is stale, so I'll go ahead and close it. For future readers, this feels a bit out of scope for what Watchtower is supposed to. If anything, it feels a bit odd that docker shuts down access to the socket **prior** to stopping the containers, or vice versa, launches containers **prior** to the socket being ready.
