### ISSUE TITLE
Request to publish Docker image with latest changes

### ISSUE THREAD

**Issue by mohanarpit** [containrrr/watchtower#1059]
First of all, thank you for this incredible project! It's been a lifesaver. 

**Describe the bug**
The `latest` tag on Docker is fairly old & doesn't reflect the code on the `master` branch. For example, I was trying to use the lifecycle hooks to prevent updates to containers based on certain conditions but it didn't work with the `latest` Docker image. This does work with Docker image with `latest-dev` tag. 

This issue is a request to see if we can publish the `latest` Docker image for watchtower.

**Expected behavior**
Expected the `latest` tag to reflect the `master` branch code 4 months after the change was published to the source code.

**Comment by tammert** [comment]
Hey @mohanarpit! `latest-dev` is actually updated each time a commit to `main` is  done -> see the workflow https://github.com/containrrr/watchtower/blob/main/.github/workflows/release-dev.yaml. Our `latest` tag is only updated on a new _release_, and we don't use it to track `main`. I'll close this issue because I don't see us changing this setup, but thanks for the feedback regardless and I hope you will be able to use `latest-dev` if you'd like to be bleeding edge? :)
