### ISSUE TITLE
Updating images for stopped containers

### ISSUE THREAD

**Issue by Umkus** [containrrr/watchtower#112]
Is it possible to explicitly update specific images, not currently running containers?
The use case is docker container being used as a cron task and not running all the time.

**Comment by stffabi** [comment]
Currently this is not possible. What would like to achieve? Would you like to have stopped container to be recreated with the updated images and just leave it stopped?

**Comment by Umkus** [comment]
That or simply pulling newer images would be fine.

**Comment by breandan** [comment]
It would be great if this worked not only for stopped containers, but all images returned by `docker images`.

**Comment by darinrogers** [comment]
Another use case is when your package manager fails silently and an app with a missing dependency gets deployed. Now the container is dead because its command won't run. Even after rebuilding and creating a new, healthy image, watchtower won't restart the stopped container with the new image. 

If it instead pulled the newer image and restarted the container with it, the dead host would suddenly come back to life.

**Comment by simonaronsson** [comment]
I can see this having a lot of hidden odd corner cases that needs to be addressed for it to work properly, especially to not make it interfer with the normal happy path. As such, it would likely require some groundwork beforehand. If you got the time and would like to have a stab at it, feel free. I'm currently preoccupied with getting the backlog back to some kind of manageable state.

I also believe we need to ask ourselves; is this really the right direction for watchtower? I'm not sure to be honest. Feel free to weigh in.

Thanks for creating an issue though! 🙏
