### ISSUE TITLE
Email Notifications - Exclude?

### ISSUE THREAD

**Issue by chasgames** [containrrr/watchtower#115]
Hello

I've got email notifications working (great addition!), but I'm also frequently getting emails for containers which are "unable to update".

I only want to receive emails to containers which have been updated. Is this possible?

Many Thanks!

**Comment by stffabi** [comment]
Currently the notification is more than just an information of updates. It's a notification system for what's going on (logging), e.g. even if errors occur. I think this is a requirement, because if someone is running watchtower somewhere on some server one doesn't want to have only an information if it updated something successfully. I personally would want to have a notification if for some case it couldn't update the container, e.g. if the server is runinng out of disk-space (well one should have another monitoring system for this of course, it's just an example).
I personally wouldn't want to have watchtower to give me the impression everything is fine and there are no updates, when essentially there was an underlying problem that it couldn't update the containers and updates are pending.
Of course there's plenty of space to improve e.g. the log-levels that are used, currently the info level is a little bit to chatty in my opinion 😄 .

`unable to udpate` shouldn't be an event which occurs everytime. If that happens often, really something doesn't work and should be investigated.

**Comment by chasgames** [comment]
Thanks for explaining stffabi! I completely understand from that point of view,

I have a few self-built containers (no private repo or anything, just from a buildfile) it's these that are unable to update, but I don't mind that.

Perhaps I should be asking a different question, how about excluding containers from the auto-update?

I know you can specify containers instead of using all within the docker daemon. I would like to have most my containers to update including new ones by default, there are just a few i don't want to update.
or am I doing something wrong in my scenario?

Thanks!

**Comment by stffabi** [comment]
Yes, for self-build image the docker pull fails. That's why you get the error. I think there is space for improvements. There's the possiblity to skip the pull, but that's a global setting, therefore this won't work if you have a mixed environment with self-build images and pulled ones from docker hub.

For filtering you can use the new `label` based filtering, see [Selectively Watching Containers](https://github.com/v2tec/watchtower#selectively-watching-containers).

**Comment by Natteverf** [comment]
Hi stffabi

Rather than opening an issue i thought i would just jump on the end of this one....
Does the email notification only work with gmail? I have been unsuccessfully trying to get the email notifications to work using postfix on the docker host but am unable to see why. I have enabled --debug but i do not see any info regarding the notifications in the logs.

Thanks for the great work!

**Comment by stffabi** [comment]
Mail notification should work with all providers. Probably you are facing the problem that version 0.2.0, which contains this functionality hasn't been released yet. Should be released soon...

**Comment by Natteverf** [comment]
thanks stffabi!
I look forward to the new release!

**Comment by stffabi** [comment]
These new features have been just released with watchtower `v0.2.0` and docker hub has been updated. 

Feel free to open a new issue if you are seeing any problems.
