### ISSUE TITLE
Customize or suppress title in notification

### ISSUE THREAD

**Issue by ksurl** [containrrr/watchtower#1207]
So the 1.4.0 release added the title line "Watchtower updates on `container hostname`" to each notification. Adding &title= no longer works for the discord webhook url. I tried changing the notification template as well to the default but it still prints it. Is there a way to customize or suppress this message like it was in 1.3.0?

_Originally posted by @ksurl in https://github.com/containrrr/watchtower/discussions/1197#discussioncomment-2052226_

**Comment by piksel** [comment]
The title param is overridden by watchtower to provide the hostname in the title field. This was only automatically done for email before, but should now be supported on several services.
It should be possible to add a prefix to the title, but that seems broken (#1205). Ideally we should provide a `NOTIFICATION_TITLE_TEMPLATE`, since the hostname is available in the template data anyway...
