### ISSUE TITLE
Log notifications are sent when using a custom template even if there are no log items

### ISSUE THREAD

**Issue by nikolas-digitalBabylon** [containrrr/watchtower#1312]
**Describe the bug**
Change in log behavior in version 1.4.0 causes notification noise

**To Reproduce**
Setup watchtower with shoutrrr notifications and set update interval to for example 90s. Every 90s a notification will be sent via shoutrrr.

**Expected behavior**
Notifications are only sent when something meaningful is communicated, e.g. a successful update or some error

**Environment**
We want to know:
 - Platform: Ubuntu LTS 64bit, vps
 - Architecture: amd64
 - Docker version: 20.10.17

In previous version (1.3.0), notifications were working as expected. Since 1.4.0, there is a log message every time the update interval times out (info level). This causes a noisy notification being sent out every single time. Besides this side-effect (notification noise), the fact that the update interval has timed out and a polling for new images will run, should not be logged on info level: this is nothing meaningful, I assume debug level would be a better choice.

**Comment by piksel** [comment]
What is the notification message you are getting? If there are no updates/failures, there should be no notifications sent.

**Comment by nikolas-digitalBabylon** [comment]
Hi, thanks for the response. 
I was getting a notification which actually had no content, as I guess was not matching my notification template. Then I checked the logs in the container. There is an info level log message just saying:
`watchtower    | time="2022-06-30T16:57:21+02:00" level=info msg="Session done" Failed=0 Scanned=8 Updated=0 notify=no` 
This is thrown at every interval and leads to a shoutrrr notification being sent. As said, the notification sent doesn't match my notification template, so practically only few of the values are populated. 

Downgrading to 1.3.0 fixes the issue. In 1.3.0 there is no such log message in the container logs, and no notification is sent.

**Comment by piksel** [comment]
I see. Those things are not strictly related. The info message being shown in the logs just informs the result of a "session" (a check/update iteration), but it's never sent as a notification. It's for logging only (hence the `notify=no`).

What I suspect is happening, is that your template yields a non-empty message when there are no updates. The notification is skipped whenever the result of the template is empty, this is so that you can customize the granularity of the messages in the templates.
It should be fairly easy to fix the template though. It's probably just a matter of adding "whitespace-eating" delimiters (`{{-` / `-}}`), but if you share your current template I can fix it.

This was indeed changed in v1.4.0 (at the same time as the info message was added), but it was intended to be non-breaking. We should extend the definition of "empty" to include messages with only whitespace as well, to not cause this issue.

**Comment by nikolas-digitalBabylon** [comment]
Yes, this is true. My notification does have content , it contains information for the host machine, which is always there. I would appreciate if you give me a more detailed example for the configuration. Nevertheless, this behavior should either be better documented (...have I missed it?), or even better, there should be no such log message. Actually I believe that the "session done with no failures or outcome" is more like a debug message than something informative.
My template actually looks like this: 
`Host ${HOST_URL}{{println}}{{range .}}{{.Message}}{{println}}{{end}}` - where ${HOST_URL} is an env var obviously always present.

**Comment by piksel** [comment]
Using this would fix your template:
```
{{- if . -}}Host ${HOST_URL}{{println}}{{range .}}{{.Message}}{{println}}{{end}}{{- end -}}
```

**Comment by piksel** [comment]
As I said, the log message is unrelated to the notifications. You might think it's not informative, but we got a lot of issues where the poster claimed that "watchtower didn't work" when the logs just said that it was starting and then silence. This shows that it ran as expected, but no updates were made.

**Comment by nikolas-digitalBabylon** [comment]
Hm, anyways, I would put it in debug level but that's just me! 

Interesting is that there was never such an issue with version 1.3.0 ,with  exactly the same setup and template.
If you believe the issue should be closed, please do so, the change in the template stops the notifications from being sent.

**Comment by piksel** [comment]
As this was not whitespace-related, it should probably be fixed by just returning an empty message when using the legacy templates and no notifiable log items was emitted during the session:
https://github.com/containrrr/watchtower/blob/30f36b3ca29f0e1b11d0be0d4ac0900faceeaeb4/pkg/notifications/shoutrrr.go#L146-L148

```go
 if n.legacyTemplate {
    if len(data.Entries) < 1 {
       return "", nil
    }
 	templateData = data.Entries 
 } 
```

This would mimic the old behavior, without needing to update the template.

**Comment by simonaronsson** [comment]
Not much more to do in this issue as we're not going to move the message to debug. Closing.
