### ISSUE TITLE
does the --cleanup option delete images with tagged with <none>?

### ISSUE THREAD

**Issue by postgetme** [containrrr/watchtower#140]
because every time pull new latest image make the former latest image tag with none

**Comment by mabanos** [comment]
I'm experiencing this issue, too.
--cleanup is not deleting the old images tagged with `<none>`

**Comment by stffabi** [comment]
Thanks for your report.

Normally --cleanup should delete those images. I'll have to investigate it and try to reproduce it on my machine.

**Comment by Codelica** [comment]
Seem to be running into this also...  Updates work fine, but no --cleanup.  Using it with to just update a single named container.

**Comment by ThePBJain** [comment]
+1 also having this issue.

**Comment by simonaronsson** [comment]
I'm not sure whether this has been solved without being referenced or if you're expecting some other behavior than the implemented one. Just tried this locally using:
```bash
docker run \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --name watchtower_test \
  containrrr/watchtower:latest --cleanup --debug --interval 10
```
and on my system it removes all images it substitutes. However, which is the bit im unsure whether you mean or not, it wont clean up OTHER images tagged as \<none\>.

Closibg as this has been dormant for more than six months. Feel free to get in touch if this is still an issue for you on containrrr/watchtower:latest. :pray:

**Comment by urza-lab** [comment]
having the same issue as described above, using `containrrr/watchtower:latest` on my ubuntu server LTS 20.04 with portainer 2.6.2 and docker-ce. my experience is that the images labelled as `<none>` stem actually from watchtower updates, but i am not sure, whether all "watchtowered" images are in the end left over as `<none>`.

i have cleared manually the unused images list and will report during the next three days on whether all updated containers leave unused `<none>` images or if those are just some of the updated ones.

_______

update1: watchtower updated 5 containers and left 4 unused `<none>` images, whereas two containers are basically the same program. i think the issue is not solved by default. is there an option in the configuration for changing this, or maybe in the stack/docker compose itself?

_______

update2: i have done some research and added the following to my docker compose:
`      environment:  
         - WATCHTOWER_CLEANUP=true`
i will report tomorrow whether this has solved the issue.

_______

update3: adding `      environment:  
         - WATCHTOWER_CLEANUP=true` solved the issue.
