### ISSUE TITLE
Config.json sample

### ISSUE THREAD

**Issue by yodamad** [containrrr/watchtower#170]
Hi

Where can we find a sample of a config.json file to provide ?

Thanks

**Comment by stffabi** [comment]
Thanks for your report. The config.json is created from docker itself, you basically mount the created json of docker `-v /home/<user>/.docker/config.json:/config.json`. For watchtower it is commonly for storing the credentials of [docker login](https://docs.docker.com/engine/reference/commandline/login/) so that watchtower could update private containers.

**Comment by yodamad** [comment]
Ok thank you, didn't get it like that. I thought it was a specific file from watchtower
