### ISSUE TITLE
[Feature Request] Update labelled images

### ISSUE THREAD

**Issue by lonix1** [containrrr/watchtower#1747]
### Is your feature request related to a problem? Please describe.

Watchtower is used to update images for *running containers*.

But we also have images which are *not always running* - e.g. console tools for our databases, infrastructure, reporting, etc. They are started on demand, by cron or by CI, perform some task, then exit. Those images are generated by our CI system in exactly the same way as the always-running images.

Watchtower doesn't update such images.

### Describe the solution you'd like

It would be nice if Watchtower could (optionally, for backwards compatibility) scan local images for a [label](https://docs.docker.com/engine/reference/builder/#label) such as `com.centurylinklabs.watchtower.enable: true`.

If found, such an image would be updated: the new version would be pulled, and the old one deleted.

### Describe alternatives you've considered

Doing it manually. Works, but unpleasant for a large infrastructure with lots of daily deployments.

### Additional context

Thanks for considering it!

**Comment by piksel** [comment]
Watchtower doesn't scan images, but rather containers. As long as you don't run the containers with `--rm` (which will remove them after exit) watchtower will update them when `--include-stoped` is used. 

See https://containrrr.dev/watchtower/arguments/#include_stopped

Or, if you don't want to keep the containers around, you can just add `--pull always` to your `docker run` command.

**Comment by lonix1** [comment]
> Or, if you don't want to keep the containers around, you can just add --pull always to your docker run command.

Excellent solution, thanks piksel!

**Comment by lonix1** [comment]
Actually that is probably a very common use case, so it would be good to have that tip in the docs. (And would avoid other people asking for the feature.)

I'll try put something together when I get a chance.

**Comment by lonix1** [comment]
After using that approach for a while, there is a downside.

The host quickly fills up with many docker images which then have to be deleted by hand. Or a cron job. Not bad for one image. But when there are many and it is liable to change, it will become a problem.

I think the solution above is actually a workaround (a good one), but isn't scalable.

---
Future readers: if you land here, how do you deal with this situation? Are there any tools like watchtower, but which do automated deployment for images too?

**Comment by polarathene** [comment]
> The host quickly fills up with many docker images which then have to be deleted by hand. Or a cron job. Not bad for one image. But when there are many and it is liable to change, it will become a problem.

That concern really depends on the frequency of image updates, their size and the available storage space.

It's more of an issue with environments like WSL where even with sparse storage enabled there seems to be some residue effect over time even after cleanup.

WSL concern aside, you can either manually invoke cleanup or setup a cron / systemd-timer to schedule that sort of maintenance. Perhaps there's an image that can do the same, but I don't see the point as you're just deferring to `compose.yaml` or some other command the equivalent of creating the scheduled task? 🤷‍♂️ 

---

- `docker image prune` will remove dangling (_**untagged**, aka older versions of the same tag_) images, provided they're not actively in use. Note, if there are containers that are stopped instead of removed, they may prevent the older image from being treated as dangling, `docker container ls -a` should help clarify that if you run into the issue.
- `docker system prune` will be more thorough if it's not just image storage that is the problem. Include the `-a` / `--all` option if you want to remove more than just dangling / unused content (_in this case pretty much everything_).
- There are other prune subcommands if you need them, `docker system df` will give you a better overview of where storage is allocated by Docker, if it's not images and you want to only address that type of storage concerning you, then use the appropriate prune command for that kind.

If your container is based off an image that has a `VOLUME` directive, that will create an anonymous volume for each container instance. If the container is not removed (_eg: implicitly after use via `docker run --rm`_), these anonymous volumes will linger. `VOLUME` is an anti-pattern IMO, but you still see it used sometimes due to a poor understanding of it. Each time that copies the internal data to a location on the Docker host, which depending on size can accumulate quite a bit.

**Comment by lonix1** [comment]
Thanks. A good list of docker housekeeping tips!

However I was hoping for an automated CD tool like watchtower. Until I find one, or watchtower supports this feature, I run a cron job with a variety of cleaning tasks (similar to what you've listed).
