### ISSUE TITLE
Slack notifications not working

### ISSUE THREAD

**Issue by MaartenMol** [containrrr/watchtower#177]
I have configured watchtower in my docker compose file with notification settings for slack, however they are not working. I get the following message in the logging:

> Failed to fire hook: Post 'https://hooks.slack.com/services/*/*/***': unsupported protocol scheme ""

I have added the "Incoming WebHooks" app to my Slack channel.

This is my docker compose part:

> watchtower:
>     image: v2tec/watchtower
>     container_name: watchtower
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock
>     command: --cleanup --interval 3600
>     environment:
>       - WATCHTOWER_NOTIFICATIONS=slack
>       - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL='https://hooks.slack.com/services/*/*/***'
>       - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=watchtower
>     networks:
>       - frontend
>       - backend
>     logging:
>       driver: gelf
>       options:
>         gelf-address: udp://172.10.2.2:12201
>         labels: com.docker.compose.project

(Sorry for weird format)

How can I solve this, am I using the wrong app in Slack?

**Comment by ystreibel** [comment]
Same error for me !
`time="2018-03-14T08:43:40Z" level=info msg="Creating /container_mysql_1"
watchtower_1  | Failed to fire hook: Post %22https://hooks.slack.com/services/XXXXXX/XXXXXX/XXXXXXXXXXXXXXXX: unsupported protocol scheme ""`

I think that you use in code webhookurl instead of webhook. check this @stffabi [https://github.com/drone-plugins/drone-slack/issues/47](https://github.com/drone-plugins/drone-slack/issues/47)

**Comment by MaartenMol** [comment]
@ystreibel I have found the issue, it's in my compose file. You need to remove the single or double quotes from the URL. Like this:

> - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=https://hooks.slack.com/services/*/*/***
