### ISSUE TITLE
Telegram notification

### ISSUE THREAD

**Issue by nsk** [containrrr/watchtower#1889]
### Is your feature request related to a problem? Please describe.

NO

### Describe the solution you'd like

integration of sending notifications and reports to a telegram bot

### Describe alternatives you've considered

none 

### Additional context

I use for speedtest tracker to see yourself you can join this channel: https://t.me/Azotespeedtestbot the bot sends a report once an hour

**Comment by piksel** [comment]
Ehm, do you mean that you want the watchtower notifications to be sent as a private message to that account?

If so, just put `--notification-url telegram://TOKEN@telegram?chats=ACCOUNTID` where the `ACCOUNTID` is your bots chat ID. You normally get it by sending a message to https://t.me/shoutrrrbot, but since it's a bot, you probably have access to it in the API.

See https://containrrr.dev/shoutrrr/v0.8/services/telegram/ for more usage information.

**Comment by nsk** [comment]
@piksel thanks is perfect : 

Azotespeedtest, [24.12.2023 17:59]
Watchtower updates on 7f03d16137bf
Sleeping for a second to ensure the docker api client has been properly initialized.

Azotespeedtest, [24.12.2023 17:59]
Watchtower updates on 7f03d16137bf
Making sure everything is sane before starting

Azotespeedtest, [24.12.2023 17:59]
Watchtower updates on 7f03d16137bf
Retrieving running containers

Azotespeedtest, [24.12.2023 17:59]
Watchtower updates on 7f03d16137bf
There are no additional watchtower containers

Azotespeedtest, [24.12.2023 17:59]
Watchtower updates on 7f03d16137bf
Watchtower HTTP API skipped.

Azotespeedtest, [24.12.2023 17:59]
Watchtower updates on 7f03d16137bf
Watchtower 1.7.1
Using notifications: telegram
Checking all containers (except explicitly disabled with label)
Scheduling first run: 2023-12-25 00:00:00 +0100 CET
Note that the first check will be performed in 6 hours, 19 seconds

Azotespeedtest, [24.12.2023 17:59]
Watchtower updates on 7f03d16137bf
Trace level enabled: log will include sensitive information as credentials and tokens
