### ISSUE TITLE
Add option to run on startup

### ISSUE THREAD

**Issue by belak** [containrrr/watchtower#189]
Right now, the only option seems to be to wait until the interval finishes. It would be nice to do a first run when the container is started and then start waiting on the interval.

**Comment by simonaronsson** [comment]
This should likely become the default behavior with the possibility of opting out (if thats even needed)

**Comment by simonaronsson** [comment]
I've been thinking a lot about this and if this could have any negative impact on any other use case. After careful consideration, I don't really think this should be added to watchtower. One (big) reason being how this would affect users running watchtower on a cron-like schedule rather than using interval. 

Also, now that `--run-once` has been implemented, you actually already have the option of running an immediate update (by running a one-off watchtower next to your scheduled one), like:

```
  docker run --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower --run-once
```

I'll go ahead and close this issue.
Thanks for taking time to report this. 🙏

**Comment by OdinVex** [comment]
It should be added anyway as an alternative to those who can't use cron due to unique environment. I've edited my entrypoint and command to immediate update then run as it normally would, the only usable work-around.

**Comment by Cheekie25** [comment]
> It should be added anyway as an alternative to those who can't use cron due to unique environment. I've edited my entrypoint and command to immediate update then run as it normally would, the only usable work-around.

Hi. Would you mind sharing your entrypoint and command ?
Would be much appreciated.

**Comment by OdinVex** [comment]
> > It should be added anyway as an alternative to those who can't use cron due to unique environment. I've edited my entrypoint and command to immediate update then run as it normally would, the only usable work-around.
> 
> Hi. Would you mind sharing your entrypoint and command ? Would be much appreciated.

I forgot what it is right off but I think it was something like: `entrypoint: "/watchtower --run-once; /watchtower"` if I recall.

**Comment by erwinkramer** [comment]
It should have been a flexible option like: 
- `trigger`, with values: `on-startup`, `scheduled` or combining values, e.g. `on-startup,scheduled`. Could even introduce more system events as trigger. 

And a separate simple option like: 
- `exit-after-run-count`, with values:  `0`, `1`, `2` etc... so u can have it exit immediately after first run (`1`) or after your first scheduled run (would be value `2`, assuming you had `trigger` with value `on-startup,scheduled`), or never exit (`0`).
