### ISSUE TITLE
synology error: "cron: panic running job: assignment to entry in nil map"

### ISSUE THREAD

**Issue by lizzard77** [containrrr/watchtower#224]
Tonight, my watchtower instance on my Synology crashed while trying to update a container (while actually there was no update available). Log file is attached.

```
2018-09-03 03:42:03	stderr	goroutine 17797 [running]:
2018-09-03 03:42:03	stderr	2018/09/03 03:42:03 cron: panic running job: assignment to entry in nil map
```

[20180903_WatchTower-log_PR.txt](https://github.com/v2tec/watchtower/files/2344361/20180903_WatchTower-log_PR.txt)

**Comment by simonaronsson** [comment]
support for synology devices and their rather special implementation of docker is currently limited as I dont have access to any physical device. if anyone running synology has a solution for this, feel free to update the wiki FAQ with how to resolve it. otherwise; maybe the synology forum/stack overflow might be able to assist you further?

closing this as we wont be able to provide any further help and im unable to reproduce the error on amd64 or on a raspberry pi.

**Comment by fr34kyn01535** [comment]
The issue seems to lay in the fetched configuration / https://github.com/containrrr/watchtower/blob/master/pkg/container/container.go#L166

`2020/02/26 15:56:51 cron: panic running job: assignment to entry in nil map
goroutine 533 [running]:
github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc000320910)
	/go/pkg/mod/github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967/cron.go:161 +0x9e
panic(0xa63940, 0xbf4880)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/containrrr/watchtower/pkg/container.Container.runtimeConfig(0x100, 0xc0002fccf0, 0xc000183ce0, 0xc0fb80)
	/home/circleci/repo/pkg/container/container.go:167 +0x3c6
github.com/containrrr/watchtower/pkg/container.dockerClient.StartContainer(0xc25520, 0xc000324780, 0x1, 0xc000130100, 0xc0002fccf0, 0xc000183ce0, 0xc000324780, 0x1, 0xc000120100, 0xc0002fccf0)
	/home/circleci/repo/pkg/container/client.go:167 +0x86
github.com/containrrr/watchtower/internal/actions.restartStaleContainer(0x8f0100, 0xc0002fccf0, 0xc000183ce0, 0xc15a20, 0xc00000cca0, 0xc00001f6d0, 0x0, 0x2540be400, 0x0)
	/home/circleci/repo/internal/actions/update.go:97 +0x1b1
github.com/containrrr/watchtower/internal/actions.restartContainersInSortedOrder(0xc000140000, 0x6, 0x8, 0xc15a20, 0xc00000cca0, 0xc00001f6d0, 0x0, 0x2540be400, 0x0)
	/home/circleci/repo/internal/actions/update.go:80 +0xb5
github.com/containrrr/watchtower/internal/actions.Update(0xc15a20, 0xc00000cca0, 0xc00001f6d0, 0x0, 0x2540be400, 0x0, 0x0, 0x0)
	/home/circleci/repo/internal/actions/update.go:46 +0x392
github.com/containrrr/watchtower/cmd.runUpdatesWithNotifications(0xc00001f6d0)
	/home/circleci/repo/cmd/root.go:183 +0xbe
github.com/containrrr/watchtower/cmd.runUpgradesOnSchedule.func1()
	/home/circleci/repo/cmd/root.go:143 +0xc2
github.com/robfig/cron.FuncJob.Run(0xc000408160)
	/go/pkg/mod/github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967/cron.go:92 +0x25
github.com/robfig/cron.(*Cron).runWithRecovery(0xc000320910, 0xc013a0, 0xc000408160)
	/go/pkg/mod/github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967/cron.go:165 +0x61
created by github.com/robfig/cron.(*Cron).run
	/go/pkg/mod/github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967/cron.go:199 +0x747
`


It would be great if the default behavior when deleting an container and trying to recreate it would atleast store the original config away, or to have all this happen before the container is deleted. As of right now this feature just deletes containers that have updates and panics.

It doesn't happen with all containers, I will inspect them and hunt for the differences.

Edit: It seems that links are in a very weird format e.g. "/eclipse-mosquitto:/home-assistant/mosquitto". I'll remove them and check if that fixes it.

**Comment by nicx** [comment]
@fr34kyn01535 have you ever solved this issue? I have the same problems :(

**Comment by l1ge** [comment]
same problem and now i have to manually reconfigure all my containers. i'll stop using watchtower because of that.

**Comment by simonaronsson** [comment]
Locking this issue as it's already closed and no one actively monitors it. We'll try our best to support different flavors of Docker, but if we're unable to reproduce the issue on any device we have access to, it's hard for us to solve the issue.

In the case of Synology's devices it's really unfortunate that they've decided to ship their own fork of Docker, just to get some fancy Web UI integration. I apologize to all of you who would like better support for your devices.

We've had limited success in reproducing the issues described in Xpenology as well, likely because it's not the exact same setup. 🤷  **If anyone would like to donate a Synology device with docker support, we'd be happy to have it as part of our test bench going forward, but other than that, there's not much we can do.**
