### ISSUE TITLE
Possible to add delay for sending the email?

### ISSUE THREAD

**Issue by 1n5aN1aC** [containrrr/watchtower#256]
So I'm getting this error when it comples updating the containers and attempts to send the email:
`Failed to send notification email:  EOF`

This is similar to #166 but I'm pretty sure it's for a different reason.  (also I am using port 587)

The problem here is one of the containers that I'm updating.....  is the mailserver itself.

Would it be possible to add a delay to sending the email to wait until it's back online before the email is attempted to be sent?  If this is not possible architecturally, I understand, but it would be nice to have!

**Comment by simonaronsson** [comment]
Thanks for your report 🙏 

Sure! Feel free to create a pull request implementing the change. I'd be happy to review it. 👍

**Comment by simonaronsson** [comment]
@piksel, what are your thoughts? would this fit into the smtp service of shoutrrr or would watchtower be a better fit?

**Comment by piksel** [comment]
It's a very specific problem, but it might be mitigated by the queueing API of shoutrrr. It would not attempt to send any mail until the container has been updated (I'm not sure exactly when that happens, since I'm not too familiar with the watchtower internals). That might be enough delay in itself.  
Otherwise, I don't think it fits into the scope of shoutrrr as a general purpose notifier, but perhaps whatchtower could add support for just waiting a little while after a container has been started before telling shoutrrr to send the enqueued messages?
