### ISSUE TITLE
Watchtower tries to authenticate against Docker Hub but image is from GitLab

### ISSUE THREAD

**Issue by fronbasal** [containrrr/watchtower#258]
Hello!
I am experiencing some issues with watchtower regarding authentication against Gitlab Registry.
I have Gitlab Registry set-up and image tags starting with `registry.gitlab.com`, yet the log states that it tries to authenticate against Docker Hub (using the credentials supplied with `REPO_USER` and `REPO_PASS`). 
How do I make Watchtower authenticate against Gitlab?

**Comment by Codelica** [comment]
Hello,

All of our images come from a private GitLab server with authentication, which as been working.  

I assume by "tags" you mean mean your full image name begins with the `registry.gitlab.com` host?  For example if you do a `docker ps` on the host do you see images like `registry.gitlab.com/<something>/<something-else>/...` ?

One other thing to try is adding `--debug` to your command arguments for Watchtower, which should give you a better idea what it's thinking. 

-James

**Comment by simonaronsson** [comment]
Closing due to lack of response.

**Comment by fronbasal** [comment]
Hello!
I am sorry for the late response.
Yes, by tag I meant the full image name.
`--debug` attempts to auth against docker hub. I will try using an up-to-date version in a fresh environment.

**Comment by simonaronsson** [comment]
If you want to utilize both private and public repos, my suggestion is that you mount `/home/<username>/.docker/config.json` in your watchtower instance rather than using `REPO_USER` and `REPO_PASS` as these env vars will be applied to all registries. However, by logging in to the repo on your docker host and then mounting the config json file, authentication will only happen for the repos that require authentication where you've also supplied it.

Exact information on how to do this is available in [the readme](https://github.com/containrrr/watchtower/blob/master/README.md).

If the problem remains even after trying that, feel free to open a new issue.
