### ISSUE TITLE
Log Level Issue

### ISSUE THREAD

**Issue by Biepa** [containrrr/watchtower#287]
Hey,
I used v2tec Watchtower a longer time.
Was it renamed? Moved? Is there somewhere info about that?

With v2tec I always got a log entry for "First Run". And also got a mail for the "First Run" log level entry.
I changed to containrrr/watchtower and when i open the log there only is one line "Attaching to watchtower", no "First Run".

Using the environment variable "WATCHTOWER_NOFITICATIONS_LEVEL=debug" changes nothing. Log still empty.

Using the "--debug" gives me more information in the log. But still no mail.

I want again to get a mail every time watchtower is started and containers are updated.

My Compose:
version: "2"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    command: --debug
    environment:
     - WATCHTOWER_NOTIFICATIONS=email
     - WATCHTOWER_NOTIFICATION_EMAIL_FROM=abc@abc.abc
     - WATCHTOWER_NOTIFICATION_EMAIL_TO=abc@abc.abc
     - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.abc.abc
     - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=abc@abc.abc
     - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=secretpassword

**Comment by simonaronsson** [comment]
Thank you for your report and your continued use of watchtower!

As the v2tec organisation no longer had enough resources to maintain the repo, it was taken over by containrrr. First run have recently been reclassified as a debug log due to user feedback classing it as too spammy. Notifications will be replaced by something (hopefully) a bit more sophisticated. Until then, no further changes will be made in the existing code.

I'll go ahead and reference that issue and close this one.

🙏 

#264
