### ISSUE TITLE
email formatting

### ISSUE THREAD

**Issue by alexanderadam** [containrrr/watchtower#354]
The default email notifications writes all changes into a single line.
It would be nice if the output would be formatted in a more readable way.

PS: Thank you for your work! :pray:

**Comment by simonaronsson** [comment]
Thanks for your report! 🙏 

The notification layer will soon be switched out to [shoutrrr](https://github.com/containrrr/shoutrrr). Because of this, I'm not really putting any effort into fixing issues in the existing implementation. The new solution, using shoutrrr, will include some more advanced customizations as templating and batching, which the current solution lacks.

**Comment by simonaronsson** [comment]
Closing this issue in favor of #264 to keep discussions and feature requests more focused.
