### ISSUE TITLE
Updatenotification when base image is updated

### ISSUE THREAD

**Issue by mlmnetcologne** [containrrr/watchtower#362]
Hi,

I want to monitor my base images of my containers. When my base image is outdated (e.g. FROM ubuntu:xenial) I want notification of it. Is this with watchtower possible, because this issue referencing it:
https://github.com/containrrr/watchtower/issues/85
but also says that it cannot work with custom images, what my container are. 
The only software that comes from the internet, are the base images. when I update my layer I build it. 
And when the container is running for months, I want to be notified when an update for the base image exists.

**Comment by simonaronsson** [comment]
Hey there!

Thank you for your report. This is not possible with watchtower the way you described it.
However, if you create a stopped container of the base image you are using and then set watchtower to monitor stopped containers as well as only monitor these containers, you'd be able to get notified whenever that image gets updated.

Exactly how to do this is described in the docs, which you can find at:
https://containrrr.github.io/watchtower/arguments/#include_stopped
and
https://containrrr.github.io/watchtower/container-selection/ (example 2, but create instead of run)

Hope this helps. 🙏 

Simon

**Comment by mlmnetcologne** [comment]
Ok thank you. 
I try it.

**Comment by mlmnetcologne** [comment]
Jay, first of all, it looks like it works, but now I have proxy Problems. Is watchtower using the proxy of the docker or how canI setup a Proxy for wt?
