### ISSUE TITLE
Multiple private registries

### ISSUE THREAD

**Issue by khor0** [containrrr/watchtower#440]
I can't find this in the documentation, so I'll assume it isn't a feature.
---

It would be awesome to declare in the configuration file which containers are to be monitored and their respective registries and credentials.

The example in [the documentation](https://containrrr.github.io/watchtower/private-registries/#create_the_configuration_file_manually) is as follows:
```json
{
  "auths": {
    "<REGISTRY_NAME>": {
      "auth": "XXXXXXX"
      }
   }
}
```

My suggestion is to have an array of containers and an option to watch over the configured ones or all, defaulting to watch over all containers and the registry to DockerHub:

```json
{
  "watchAll": true,
  "containers": [
    {
      "name": "container-name",
      "interval": 10,
      "registry": {
        "name": "registry.gitlab.com",
        "username": "username",
        "password": "password"
      }
    }
  ]
}
```

**Comment by simonaronsson** [comment]
Thank you for your report! 🙏🏼

Unfortunately, the configuration file mentioned in the documentation is part of docker rather than watchtower, so such a change would require changes in moby/moby as well.

Is there a specific use case you're trying to solve that is currently not covered by watchtower? If so, it would be interesting to check whether we could find an alternative approach to achieve what you need.

**Comment by khor0** [comment]
Hello there @simskij. Thanks for the fast response.

I have a server which contains multiple dockerized applications owned my multiple people/project groups.

As a sysadmin, I would rather have a Key on the server end which has read rights for the registry (in this case GitLab's) than have SSH keys deployed into the repo to execute commands inside the server.

I already use a simple instance of Watchtower with a self-hosted GitLab deployment. As it works very well, I would like to differentiate multiple registries for the projects and also 'attachments', such as databases.

If I my explanation was confusing, feel free to say so!

Thanks again

**Comment by simonaronsson** [comment]
Got it! Thank you for the explanation!

For the time being I, unfortunately, have no plans on adding such a feature. This is more due to lack of time than anything else, so if you'd like to have a stab at providing a PR I'd be more than happy to assist you through the process.

The easiest way to do this would likely be to add a `WATCHTOWER_SCOPE_UID` env var, to be able to differentiate between different watchtower instances, and then set multiple instances with different scopes and keys. It would also have the added benefit of being a lot more resilient than just adding programmatic support for one instance to use multiple configs.
