### ISSUE TITLE
Download new image but don't update?

### ISSUE THREAD

**Issue by jazozaya** [containrrr/watchtower#467]
Hello,

I am wondering if it is possible to have watchtower automatically detect and download new images, but NOT restart or kill the running containers?

WATCHTOWER_NO_RESTART seems to pull and update the images but stops the running containers
WATCHTOWER_MONITOR_ONLY seems to be meant for notifications.

We will be using docker container to run a server for a '3d printer', so having a container restart in the middle of the print is unacceptable.

Ideally the new images would be automatically downloaded and a new container would be started on the next boot or when a user shutsdown the app. 

Regards,

**Comment by simonaronsson** [comment]
Hi, and thank you for your report! 🙏🏼

Unfortunately, there is no such option at this point. If you're open to providing a pull request adding it, I would of course help reviewing and make sure it reaches master, but the sad reality is that my time is too limited to undertake this at this point.

A workaround would be to schedule updates for a window when you know you wont be printing using the built in schedule option, which takes a cron expression.

**Comment by mlmnetcologne** [comment]
WATCHTOWER_MONITOR_ONLY:
Watchtower detects the new image when atemting to download the image of exiting containers, after that we have to recreate the containers ourself, to use the new image. 
This is because we have to test, if the new image still works with our software. 
So this happens:
1. watchtower try to pull the latest image of the container
a. detects that the container is using the an old image, sends "New image found..." as a notification
b. detects that the container is using the latest image, sends "up to date" as a notification
2. We see the notification and starting our update process (just a)
... we have to recreate the container manually with the latest image.

Hope this helps you while the as I call it "CREATE_NEW_CONTAINER" (instead of recreating the container, there are two) or "WAIT_SHUTDOWN" (waits for the container to stop) Feature is not implementet or even written yet. 
What you could do is, when the watchtower notify you, this could trigger an automatic prozess (like above)?
When I have much more time I could look into this feature. (likely in mid-April)

Stay healthy and at home, when you can,

Maurice
