### ISSUE TITLE
Local and remote docker host monitoring

### ISSUE THREAD

**Issue by talondnb** [containrrr/watchtower#506]
**Describe the solution you'd like**
I've recently moved to watchtower from ouroboros and would like to monitor both a local socket and remote docker host socket with watchtower. Unfortunately it doesn't look possible, could this please be added as a feature?

**Describe alternatives you've considered**
Ouroboros but it is no longer in active development. Otherwise perhaps running two separate docker containers but this does not feel efficient.

**Additional context**
N/A

**Comment by simonaronsson** [comment]
Hey there and welcome to the community! 🙌 

We're currently working on providing support for multiple instances of watchtower in . Remote support is already available as described [here](https://containrrr.github.io/watchtower/remote-hosts/), although your local instance might very well kill that one during the start up phase, pending the multiple instance support.

We've actually opted for the multiple instance approach over providing support for watching multiple hosts from one instance, out of multiple reasons:

1. It separates concerns and makes it easier to reason about.
2. It provides a more resilient service, as errors will never have opportunity to propagate.
3. Watchtower is extremely lightweight, especially compared to ouroboros (mostly due to the choice of language I think), and resource consumption should likely never become a problem.

Does that make sense? If not, I'd be very happy if you could explain your use case in greater detail so I understand what I'm missing. 👍

**Comment by dearekaelle** [comment]
for one, if a single instance was able to monitor both local and remote sockets, it potentially could take care of dependencies between the containers running on multiple docker hosts, in which case it would start/top/update them in proper order? 
I see a use case here, I am currently running multiple watchtower instances on each host, but would be nice if updating my db container would restart dependent containers.
