### ISSUE TITLE
Add a flag to show auth values in plaintext for debugging purposes

### ISSUE THREAD

**Issue by simonaronsson** [containrrr/watchtower#539]
This should be off by default, and clearly require some effort, like; `--show-password-in-plaintext --i-accept-the-associated-risk` both being present

**Comment by simonaronsson** [comment]
Continuation of #537 and #517

**Comment by tammert** [comment]
I can pick this up as well, feel free to assign it so me.

Had a thought on this too: maybe instead of a very specific flag (disclaimer: I'm not a big fan of many niche flag options :sweat_smile:), we could use the Trace log level already provided by Logrus?

I realize that this would actually still add an extra flag (`--trace`), but it seems realistic for Trace to print credentials, whereas it's probably a bit too much info for Debug. Might be handy in the future too for some niche logging statements.

@simskij let me know what you think, I don't mind implementing it either way!

**Comment by simonaronsson** [comment]
Sounds good to me! 👌🏻
