### ISSUE TITLE
Warning about new schema

### ISSUE THREAD

**Issue by herkalurk** [containrrr/watchtower#547]
When launching watchtower recently I received a warning about upgrading the schema of the dockerfile, just thought you should know.

```
[user@host watchtower]# docker-compose up -d
Pulling watchtower (centurylink/watchtower:latest)...
latest: Pulling from centurylink/watchtower
Image docker.io/centurylink/watchtower:latest uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
a3ed95caeb02: Already exists
802d894958a2: Already exists
411fca6de37d: Already exists
Digest: sha256:1b208177d603af4bad6d64c77baf59e5dd166db18d1ad87853a91801ace66ce7
Status: Downloaded newer image for centurylink/watchtower:latest
Creating watchtower ... done
```

**Comment by zoispag** [comment]
This is not an official watchtower image. This is maintained by centurylink.
Is this yours? Is it a recent mirror?

**Comment by herkalurk** [comment]
I don't have any images on docker.  The image I listed has this git repo on their page at [dockerhub](https://hub.docker.com/r/centurylink/watchtower/).  If they aren't going to keep things updated then I will switch to your release.

**Comment by simonaronsson** [comment]
Hi, and welcome!

Unfortunately, it's not possible for us to take down that image. The CenturyLink image has not been updated in five years, so I suggest you start by changing to `containrrr/watchtower`, which is the official repo since more than a year.

If you still have issues after that, feel free to open a new issue.

Thanks,
Simme
