### ISSUE TITLE
Per-container setting if update or only notify

### ISSUE THREAD

**Issue by gtrs** [containrrr/watchtower#582]
**Is your feature request related to a problem? Please describe.**
Updates can always break something. There are two classes of containers: containers where a failed update can have catastrophic consequences and containers where a failed update is annoying, but less critical. For the first class, you only want notifications, for the second, automatic updates are fine.

**Describe the solution you'd like**
It would be nice to use labels to set an update/notify-only policy per container similar to the enable/disable feature. For example:
`com.centurylinklabs.watchtower.monitor_only=true`

**Describe alternatives you've considered**
- Don't enable watchtower for critical containers
- Two watchtower instances, one that runs updates using label-enable filtering for the non-critical containers, another one that watches all containers, but is set to notify only (you will get redundant notifications)

**Comment by simonaronsson** [comment]
This is a great suggestion. Per-container settings through labels would sure be a nice addition. Would you like to have a stab at implementing it? I'd be happy to provide assistance and review your code.

**Comment by ogmueller** [comment]
I really like this feature and we are already trying to use it, but it doesn't seem to work fully.

Our approach is probably a bit reversed though. We want to "whitelist" those containers, which can be updated/restarted automatically, instead of "blacklisting" the critical ones. So we like to set watchtower itself to `WATCHTOWER_MONITOR_ONLY: "true"` and label the non-critical containers with `com.centurylinklabs.watchtower.monitor-only=false`. Watchlist pulls and informs about a new update, BUT is not restarting the container anymore.

I am not sure, if watchtower needs another label `com.centurylinklabs.watchtower.no-restart=false` OR if `com.centurylinklabs.watchtower.monitor-only=false` should also re-set` WATCHTOWER_NO_RESTART` to `false` again.
