### ISSUE TITLE
Inspect images without pulling them?

### ISSUE THREAD

**Issue by prabuvenkat** [containrrr/watchtower#607]
Use [skopeo](https://github.com/containers/skopeo) maybe? or, something along [these lines](https://ops.tips/blog/inspecting-docker-image-without-pull/)

**Comment by zoispag** [comment]
@prabuvenkat to what end? What do you want to achieve?

**Comment by prabuvenkat** [comment]
To pull images only if there are any updates? 

I understand from the documentation that the comparison is made _after_ pulling the image, as of now. Or, have i missed something?

I would not want to squander away pricey vps bandwidth and storage with docker images.

**Comment by simonaronsson** [comment]
We'll have to dig into how skopeo works to have an educated opinion.

At a glance, trying to build something that compares the image hashes without pulling it seems error prone and unlikely to work with all flavors of registries. If that is not the case and the implementation is reasonable enough, I don't see why we couldn't pursue this.

@containrrr/watchtower-contributors any thoughts?

**Comment by simonaronsson** [comment]
@prabuvenkat
Oh, and as a side note, it would be great if you'd use the issue template for feature requests next time. It's there to give us enough information about the rationale, as well as alternatives considered, from the get-go, without having to ask. Thanks 🙇

**Comment by victorcmoura** [comment]
> @containrrr/watchtower-contributors any thoughts?

Well, I got interested in contributing to that API feature exactly because of this active behavior that forces Watchtower to make network usage in a fixed interval.

But, even though I see it as an issue, simply inspecting the Docker image without "pulling" it wouldn't be much of an improvement. If the whole image actually got pulled on every interval, it would make complete sense, but as Docker layers are cached, if there is no drift between the remote and the local images, there won't be any considerable network usage other than a few requests to fetch metadata. So, in practice, the usage of resources would be pretty much the same.

If you have some sort of SLO that requires you not to exceed a specific amount of requests or network usage, and you consider that Watchtower has some sort of impact on it, I recommend you to use the HTTP API feature, so you can trigger your updates based on external features, such as a git commit, merge request approval or even a Docker image push.

**Comment by victorcmoura** [comment]
Update: https://github.com/containrrr/watchtower/discussions/631

**Comment by zoispag** [comment]
Up

**Comment by simonaronsson** [comment]
I've gone through the docker client code, and wrote about my findings in https://github.com/containrrr/watchtower/discussions/668#discussioncomment-116021

The TL;DR is that the docker client already handles this and that watchtower checking for image updates won't lead to the full image being downloaded every time. Unless there's an actual change, only the SHA digest is fetched through an HTTP HEAD request.

Using the watchtower repository as an example, the full response is:

```
HTTP/1.1 200 OK
Content-Length: 4918
Content-Type: application/vnd.docker.distribution.manifest.v1+prettyjws
Docker-Content-Digest: sha256:e24b7c874f4e514676a3aeca424ed55a03d32ea1095925d8e37f910bfea3d782
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:e24b7c874f4e514676a3aeca424ed55a03d32ea1095925d8e37f910bfea3d782"
Date: Thu, 29 Oct 2020 20:55:34 GMT
Strict-Transport-Security: max-age=31536000
```
