### ISSUE TITLE
Why does watchtower make so many requests to registry-1.docker.io

### ISSUE THREAD

**Issue by yurividal** [containrrr/watchtower#660]
My watchtower makes thousands of requests per day to registry-1.docker.io

![image](https://user-images.githubusercontent.com/8555749/95657195-0288d600-0b0b-11eb-9832-ce880fd5b9b1.png)

Wheni disable this container, the requests to docker reduce. I dont need watchtower to check updates every minute. what's wrong?

**Comment by victorcmoura** [comment]
Hi, @yurividal! Watchtower natively works by checking periodically for updates. You can adjust how frequently it polls through the [Poll Interval argument](https://containrrr.dev/watchtower/arguments/#poll_interval). By default, this argument is 300s (or 5min), which results in 288 requests per day (or 25.920 in 90 days, which is the time period you've used as a reference).

Given this context, you have two options:
- Keep using the interval-based polling (and maybe reduce the polling frequency);
- Use the [HTTP API Mode](https://containrrr.dev/watchtower/http-api-mode/);

With HTTP API Mode, instead of actively looking for the updates, Watchtower exposes an endpoint that can be requested to trigger a one time check. You can develop your own logic to request this endpoint and trigger an update. These are a few use cases:
- If you have a CI job that pushes new images to DockerHub, create a next job that requests your Watchtower instance to tell it when new updates are available;
- If manual deployments suit better for your context, create a script or a form button that sends a request to your Watchtower instance, triggering the update;

I hope it can help you understand and, maybe, even optimize your Watchtower setup :)

**Comment by yurividal** [comment]
It's set to 90 days but this DNS is actually only 2 weeks old.
45 thousand in 2 weeks.

Anyways, I'll try to set the WATCHTOWER_POLL_INTERVAL to once per day, and I'll see if it solves

**Comment by Kopernikus1979** [comment]
Same here, saw it in my Pi-Hole statistics it's indeed every 5 minutes, but it makes 32 A & AAA request instead of 1, so instead of 288 request a day they are 9216 request a day.... I think there's something wrong there...

``

**Comment by zoispag** [comment]
> Same here, saw it in my Pi-Hole statistics it's indeed every 5 minutes, but it makes 32 A & AAA request instead of 1, so instead of 288 request a day they are 9216 request a day.... I think there's something wrong there...
> 
> ``

How many containers does watchtower monitor?

**Comment by Kopernikus1979** [comment]
6 containers including watchtower

**Comment by yurividal** [comment]
Mine seems to be working fine after I set the Poll Interval manually to 43200  (12 hours). I see about 17 requests twice a day now. Much lower than the thousands a day I was seeing.
Still, not sure why it needs 17 dns requests to the same address every time it runs. (I have 5 containers including wt)

![Screenshot_20201017-002419_Samsung Internet Beta](https://user-images.githubusercontent.com/8555749/96321989-413cf580-100f-11eb-8dd8-e8cc1985e86d.png)

**Comment by piksel** [comment]
Watchtower itself doesn't access the registry, but rather tells the docker daemon to do so. You can limit how often this happens, but I don't think we can do anything about the number of lookups that each check does.

**Comment by Kopernikus1979** [comment]
Hi,

No problem I will set the Interval manually to 43200.

Thx

**Comment by simonaronsson** [comment]
If you prefer cron expressions over configuring intervals, you could use the [`--schedule`](https://containrrr.dev/watchtower/arguments/#scheduling) argument instead.

Closing this issue as a clear workaround path has been provided.
Thanks you for contributing!
