### ISSUE TITLE
Are App-Data retained during update?

### ISSUE THREAD

**Issue by oywino** [containrrr/watchtower#67]
The intro reads: _Watchtower will pull down your new image, gracefully shut down your existing container and restart it with the same options that were used when it was deployed initially._
That's fine, but what about local App-Data created over time while the container was running and stored inside the container? Are those data retained as well?
I understand that data stored in mapped folders (external volumes) are untouched, but what about config and setting files stored inside the container itself ? Are they kept alive or lost?

**Comment by stffabi** [comment]
It's not possible to keep in-container data. Docker itself doesn't provide any way to achieve this, docker can't update a running container to another (new) image version. The "docker" way to upgrade a container to a new version is to create a new one, therefore all data stored in the container itself is lost, and that's why you need to manage all app data with mapped folders or with volume containers. Storing application data in the container itself is seen as an anti pattern in docker. Please see [1](http://stackoverflow.com/a/26833005) and [Manage data in containers
](https://docs.docker.com/engine/tutorials/dockervolumes/) and [Docker Container Anti Patterns
](http://blog.arungupta.me/docker-container-anti-patterns/)

**Comment by oywino** [comment]
@stffabi,
Thanks for your reply. However, as an ordinary user I have very little influence over where various apps store such data. The Apps themselves have no knowledge of the fact that they run inside containers, and they store config data, index files, temp data etc, here and there close to its own feet.
Thus a restarted app always start by asking for user data and basic settings all over again as if newly installed, and everything done over time is lost, except the main DB which is external.  Regretfully, in most cases the external DB becomes useless and is often automatically cleared and deleted when the mother app is reset (restarted).
Consequently - we're faced with a gap between theory and reality, right?

**Comment by stffabi** [comment]
To be honest, in such cases the container images are not well designed. I've used a lot of different container images and have never seen a lot of problems regarding this. Building containers is not an easy task and has to be carefully done. This starts with automatic configuration in the container boot-strap script up to carefully define the correct mountpoints for persistence storage.

May I ask what image you are using, for which you have these problems?

**Comment by stffabi** [comment]
Maybe you could let the maintainer know about your problems or ask him for help?
