### ISSUE TITLE
Trigger container restart via WebHook

### ISSUE THREAD

**Issue by andreo** [containrrr/watchtower#7]
Hi, instead of checking for the changes every N seconds, it would be nice to trigger container's restart once new image has been pushed successfully to the docker hub etc. Any ideas how to implement this?

**Comment by amcsi** [comment]
I would also like this to happen. Polling is generally bad practice. Plus it now shows that I have over 2K pulls of my own image, which isn't very useful data.

**Comment by nafg** [comment]
Well, Docker Hub has a Webhooks tab, so if the watchtower container could expose a public http endpoint you could configure docker hub to ping it... but that would only help for repositories that you control. At least it could be an option...

Another idea: I guess currently watchtower just executes a local `docker pull` (regardless if it's via cli or daemon api)? So how about using this API on the registry directly: https://docs.docker.com/v1.6/registry/spec/api/#pulling-an-image-manifest (or the v1 https://docs.docker.com/v1.6/reference/api/registry_api/#get-image-layer_1)? Do hitting those increment the number of pulls Hub shows?

**Comment by amcsi** [comment]
I am only interested in the images I control, because those are the ones I am developing, and I would like to have a workflow that pushing to master deploys to production.
And yes my dockerhub project having 10k pulls even though no one knows or cares about the project seems evident. But that's the smaller issue.
Currently it takes about 5 minutes per project to be built automatically on Dockerhub, so with the 5 minute polling I have set up with watchtower, each push to master can take potentially up to 10 minutes to get deployed when that time could be halved with webhooks.

**Comment by stackdump** [comment]
I found that watchtower didn't really fit my needs for this use case so I ended up using a python web hook  + an ansible playbook  that pulls and updates containers from dockerhub.

https://github.com/stackdump/docker-ansible-webhook

_EDIT_ my only issue was that watchtower pulls incremented the counter on dockerhub ( really just a personal hangup )

**Comment by simonaronsson** [comment]
This issue is very closely related to #262 and will as a result be closed.

**Comment by tuukka** [comment]
The solution from #262 makes it possible to trigger via an additional service, but I wish this could be re-opened to potentially have an integrated solution in the future.

**Comment by thebrucecgit** [comment]
This feature would be amazing, and saves a lot of resources that's used by polling.

**Comment by simonaronsson** [comment]
The issue with download count rising because of watchtower polling was solved with the introduction of head-based digest checking. If you want to suggest anything else, feel free to raise a new ticket.
