### ISSUE TITLE
Honor containers individual --stop-timeout

### ISSUE THREAD

**Issue by sixcorners** [containrrr/watchtower#733]
**Is your feature request related to a problem? Please describe.**
This doesn't seem to pay attention to the --stop-timeout I have set on some of my containers.

**Describe the solution you'd like**
I would like this to wait until the --stop-timeout on the container is reached before killing it.

**Comment by piksel** [comment]
There is a [stop-timeout](https://containrrr.dev/watchtower/arguments/#wait_until_timeout) argument (and environment variable) that you can add to watchtower to do this for all the containers being updated.

But yeah, there is currently no support for using the currently running containers stop timeout. It might be due to it being a newer feature (API v1.25+) and we need to use the lowest commonly used API version. If that's the case, then this cannot be implemented until we update to a higher lowest API version.
