### ISSUE TITLE
Watchtower HTTP API flag documentation is incorrect

### ISSUE THREAD

**Issue by it4mag** [containrrr/watchtower#786]
**Describe the bug**
When running the container with WATCHTOWER_HTTP_API or with the flag --http-api, the container do not start and the error in the logs says the --http-api flag is incorrect

**To Reproduce**
Start the container with --http-api flag

**Expected behavior**
Watchtower is launched in HTTP API mode

**Solution**
The container starts in the correct mode if provided with the flag --http-api-update or the environment variables WATCHTOWER_HTTP_API_UPDATE. The documentation should be updated accordingly

Best Regards

**Comment by it4mag** [comment]
Another issue : the token seems to not be taken into account when triggering with curl

**Comment by piksel** [comment]
Yeah, you're right, the arguments changed in 1.1.6, but the documentation wasn't updated.

Are you saying that it's not checking the token (provided with `---http-api-token` or `WATCHTOWER_HTTP_API_TOKEN`)?
Does it allow all requests or none?

I think I know what is happening, in the current documentation it says that the token should be provided using:
```Token: <TOKEN>``` header, instead of the [standard](https://tools.ietf.org/html/rfc6750) ```Authorization: Bearer <TOKEN>``` header.
I think this was changed as well, but it seems like a breaking change, so in that case maybe we should support both?

**Comment by rolfwessels** [comment]
👍 Had same issue. @piksel thanks for the info

**Comment by it4mag** [comment]
Yes it was the header that was changed. I fixed my implementation without warning you here sorry

**Comment by simonaronsson** [comment]
> it seems like a breaking change, so in that case maybe we should support both?

Fixing the docs should be enough. We can't really keep compatibility alive forever and this was only live for a couple of versions before it was changed, so the amount of users that actually have implemented something using `Token` instead of  `Bearer` are likely very few.
