### ISSUE TITLE
eMails Notifications : add color and some formating

### ISSUE THREAD

**Issue by MilesTEG1** [containrrr/watchtower#815]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to have some colors and formatting in the email notifications I received from watchtower to emphasis some text in the condense text.
Currently, I have this :
![image](https://user-images.githubusercontent.com/29298312/107187141-d1031700-69e5-11eb-8f66-b7ce92016a15.png)

**Describe alternatives you've considered**
Some colors and formatting like this :
![image](https://user-images.githubusercontent.com/29298312/107187833-e9276600-69e6-11eb-9fb9-28356bec43da.png)

**Additional context**
Cf. before.

**Comment by piksel** [comment]
The way the notifications are set up right now, this is not currently possible. But I do agree that highlighting the variadic parts of the messages is really useful ([this](https://archivediagstore.z16.web.core.windows.net/reports/MT1JFFjgcE2DvI0ho8Duxw.html) is the output from my archive diagnosis tool).

Since there are only a small set of messages, this might be possible to do with regex post-processing of the messages.

In any case, the e-mails will need to be sent in HTML format and not in plain text as they are now. This option is at least something I have planned to work on somewhat soonish.

**Comment by fepas** [comment]
@piksel 

Is there a specific reason why emails are not yet sent in HTML format? From what I saw I believe that Shoutrrr is responsible for this type of notification, so it would be a limitation related to Shoutrrr? If yes, it would be interesting to add HTML format to Shoutrrr emails?

**Comment by piksel** [comment]
Shoutrrr supports it, it's just a matter of adding a HTML template for the e-mails. I plan to include a basic one inside Shoutrrr that just wraps the content in a box for general use, but ideally Watchtower should have it's own template.

![image](https://user-images.githubusercontent.com/807383/109794320-092cfc80-7c16-11eb-8923-e4a756b2e29f.png)

**Comment by simonaronsson** [comment]
If anyone would like to have a stab at this, feel free. I'd be happy to assist with reviews and such.
