### ISSUE TITLE
Rebuilding custom images on changes of their base image

### ISSUE THREAD

**Issue by DMW007** [containrrr/watchtower#85]
First of all: Watchtower is a great software to care about updates for application containers, which is an important feature to avoid security holes by running outdated software. For containers that can be run directly, it provides a great job. 

But it seems failing, when we're building a custom image. I need this for example on PHP, to include extensions which are not installed by default, like the MySQLi-Extension, which is required to run a wordpress app. 

To solve this, I've a docker-compose file which nginx and php-fpm. Nginx doesn't need any modification, so I refer the image directly. But for PHP I included a custom Dockerfile like this: 

```
 php:
    container_name: wp-hosting-php
    restart: always
    mem_limit: 512MB

    build:
      context: ./php7-fpm
```

Now I have a `Dockerfile` in the `php7-fpm` folder that is based on the official PHP Docker image, but installs required extensions like MySQLi in this example: 

```
FROM php:7.1-fpm
RUN apt-get update && \
        apt-get install -y libmysqlclient-dev \
        mysql-common
RUN docker-php-ext-install mysqli
RUN docker-php-ext-configure mysqli --with-mysqli=/usr/bin/mysql_config
```

In this case, `docker ps` doesn't show me the `php:7.1-fpm` image for this container. Docker seems to generate an image name automatically in the scheme `<FolderName>_php`.

It would be very nice to have watchtower handling those containers, too. Especially on PHP, where we have a lot of (security) patches, which should be installed soon to keep the applications as secure as possible. But since watchtower uses the Docker socket to get his information, I'm not sure how we could handle this. It seems hard to get this information from docker directly. 

### Possible workaround

As an alternative, I had the following idea: Creating a system-wide php image for me, that contains all extensions for any applications. This would blow up some containers a bit, but I think that's insignificant. And we have the benefit, that this image (lets call it `php-7-fpm-global`) can be build automatically using a cron job, lets say every hour. 

Then there is the question, if watchtower detects those changes? 

I saw the option switch `--no-pull ` with watches local image cache for changes. So when my cron runs, it detects that a new update of `php:7.1-fpm` is avaliable and rebuild my shared image `php-7-fpm-global`. Now watchtower updates all my php containers, which are using this version? And the big question: Does watchtower this _only_ with the `--no-pull ` switch? Or is watchtower doing this already without it, so that without the switch he fetches online images _and_ watches local images for changes? The first case would be not so good, since it requires me to use two watchtower instances, one for online images and another one for my local build custom ones.

**Comment by ntninja** [comment]
I have the same problem: Somebody has a WordPress-based website, that connects to a PostgreSQL database (the setup involves some black magic and *interesting* plugins – don't ask), so I've derived a custom WordPress image from the [official one](https://hub.docker.com/_/wordpress/) that includes the `pgsql` PHP extension.

Maybe watchtower can do something similar to docker-hub? Try to pull the parent container and, if it is indeed a new version, rebuild the child one?

Specifically something like this could work:

  1. Check for each container whether it has a new, special label (e.g.: `v2tec.watchtower.rebuild`)
  2. If a container with the `v2tec.watchtower.rebuild` label is encountered, assume that it is a locally built container and check its parent image instead of the container's actual image for new revisions
  3. If a new revision of the parent image is available pull it, then call (the API equivalent) of `docker build` for the value of the `v2tec.watchtower.rebuild` label of the container to rebuild the container's image
  4. Restart the container if the newly built image

@DMWOO7: (Just in case) You can work around your problem by using the WordPress official image (tag `4.8-php-7.1-fpm` most likely in your case) instead of the PHP base image and replacing its WordPress installation with your own. This falls apart if you need any more fancy extensions of course…

**Comment by DMW007** [comment]
Yes I need some extensions. I found out that watchtower doesn't watch local images by default, it gives the error `repository php7.1-fpm-extended not found: does not exist or no pull access`. But it's theoretically possible to workaround this by starting a second watchtower container with command `--no-pull`. In practice not, cause the second container detects the first one and kill it: 

    time="2017-12-23T15:35:09Z" level=info msg="Stopping /watchtower (9671b004cbf86336a5b42e862a1a9b13dc631b2dfee22e362a860a310d56ed67) with SIGTERM"

**Comment by DenSA-Inc** [comment]
I'm feeling the need to update local images too. All I could find was a script on stackoverflow repeatedly polling the base image version from the docker hub and comparing it to the local image version. Here it is: https://stackoverflow.com/a/26548914
I guess combining it with https://github.com/Wiredcraft/docker-builder would be possible to avoid having to implement all the logic of rebuilding your containers.
And to avoid the "repository not found"-error i'd setup my own docker image registry (which only requires you to run the registry-container). That way you can use unique image names that don't clash with existing ones.

Keep in mind it's late here. I'll look over all of it again tomorrow.

**Comment by DenSA-Inc** [comment]
When i'm thinking about this i came up with 2 features watchtower should have.
First there is the ability to watch images not used in containers. In order to poll new versions of base images I could use the SO-script mentioned before, but integrating this feature into watchtower should be a reasonable addition.
Second there is the option of using webhooks, similar to docker hub. There already exists a way to notify the user via email when an image gets updated. Adding the functionality to post to an url instead of sending an email should not be that hard. (Even though the notification environment-variables have to be adjusted)

With these two features one would be able to watch base images and configure a webserver to rebuild ones custom images when the webhook gets called. Then, with the next watchtower-poll, the containers will be updated with the new custom images.

**Comment by ntninja** [comment]
@DenSA-Inc: Yeah, as mentioned above I had the same issue and I solved it by writing my own script that IMHO makes this quite painless: https://gitlab.com/alexander255/docker-image-rebuilder

Basically you give it a simple configuration file ([sample](https://gitlab.com/alexander255/docker-recipies/blob/master/docker-recipies.toml)) that tells it:

  1. Which `Dockerfile` to rebuild
  2. Where to push the result (multiple targets possible)
  3. (Optionally) Which image files to are considered “unimportant changes”/“volatile”

And it will attempt to (1) rebuild those images and (2) push the result *if any of the files in the image actually have changed*.
Combine that with [Docker's local registry](https://docs.docker.com/registry/) and watchtower service and you have a complete pipeline that will regularily rebuild and run all your image modifications (and optionally even distributes them for others to use).

**Comment by simonaronsson** [comment]
@alexander255s suggestion is probably the least painful approach to this.
imho, this is not something that watchtower should even aspire to solve as it would require rebuilding the image. thanks for creating an issue however and feel free to get back in touch if you have any questions or suggestions.

🙏

**Comment by wedi** [comment]
You can solve this by running your own registry and pushing your images to it:

```shell
$ docker run -d -p 5000:5000 --restart=always --name registry registry:2
```

As [the docs state](https://docs.docker.com/registry/deploying/), this example does not secure the registry, neither login nor tls but it should work in a private setup.
