### ISSUE TITLE
-e WATCHTOWER_NOTIFICATION_EMAIL_FROM_NAME="[My fancy watchtower bot]" 

### ISSUE THREAD

**Issue by jobenvil** [containrrr/watchtower#887]
**Is your feature request related to a problem? Please describe.**

Actually there is no possibility to send mails from other name than "Watchtower". That's hardcoded in `fromname=Watchtower`

Here is an example of the received mail:

![image](https://user-images.githubusercontent.com/11994245/114088884-cd8cee80-98b5-11eb-91f6-cfbd642d390a.png)

**Describe the solution you'd like**

Actually I would like to make the _email name from_ more specific, like "`[Watchtower Bot]`". Here an example with `alertmanager`

![image](https://user-images.githubusercontent.com/11994245/114089343-51df7180-98b6-11eb-9957-5952112eacdd.png)
 
**Describe alternatives you've considered**

Add an environment variable like 

`WATCHTOWER_NOTIFICATION_EMAIL_FROM_NAME`

in my specific case would end, i.e.: 

`WATCHTOWER_NOTIFICATION_EMAIL_FROM_NAME="[Watchtower Bot]"`

**Additional context**

Not proceed.

**Comment by piksel** [comment]
If you use the shoutrrr URL (`WATCHTOWER_NOTIFICATION_URL`) instead of the `WATCHTOWER_NOTIFICATION_EMAIL_*` environment variables you can set the sender name.

Example:
```
WATCHTOWER_NOTIFICATIONS=shoutrrrr
WATCHTOWER_NOTIFICATION_URL=smtp://user:pass@mailserver.com:465?fromAddress=sender@mail.com&fromName=Alertmanager+Bot&toAddresses=reciever@mail.com
```

To help generating the correct URL you can look at the [documentation for the Email service](https://containrrr.dev/shoutrrr/services/email/) or use:
```
$ docker run --rm -it containrrr/shoutrrr generate smtp
```
or to just verify that your URL is correct:
```
$ docker run --rm -it containrrr/shoutrrr verify "smtp://user:pass@mailserver.com:465?fromAddress=sender@mail.com&fromName=Alertmanager+Bot&toAddresses=reciever@mail.com"
```

<details>
<summary>(output from <code>shoutrrr verify</code>)</summary>

![image](https://user-images.githubusercontent.com/807383/114096335-dfbf5a80-98be-11eb-9fe3-7937cc810cd4.png)

</details>

**Comment by jobenvil** [comment]
Indeed, I tried with `WATCHTOWER_NOTIFICATION_URL=smt://...` but I missed the entry `WATCHTOWER_NOTIFICATIONS=shoutrrr`. I was not aware of [email notifications with shoutrrr](https://containrrr.dev/shoutrrr/services/email/) and compatibilities. 

Thanks to your detailed answer, I was able to tune the mail notification, further more than I was expecting:

![image](https://user-images.githubusercontent.com/11994245/114194738-11343680-9950-11eb-972a-6d5bb03fd705.png)

Thanks a lot @piksel for helping me out!
