### ISSUE TITLE
Add actually useful metrics

### ISSUE THREAD

**Issue by laurivosandi** [containrrr/watchtower#973]
**Is your feature request related to a problem? Please describe.**
I added watchtower to our infra and I saw that the bug for Promtheus metrics was closed so I expected to have some useful metrics to alert upon - a'la how many containers are out of date. At this point I really don't feel comfortable with any kind of automated container updates.

**Describe the solution you'd like**
I want metric which would count how many containers are out of date

**Describe alternatives you've considered**
Getting notified via e-mail about updates is not really working solution for me. All the alerting is already consolidated into prometheus/alertmanager. Reimplementing alerting in watchtower itself seems excessive.

**Comment by laurivosandi** [comment]
Also looks like Prometheus metrics are incorrectly reporting `watchtower_containers_updated`. Prometheus metric reports 8, but in fact no containers were updated. Looks like more correct name for this metric would be `watchtower_containers_pulled`

**Comment by piksel** [comment]
I presume that you are running with `MonitorOnly`, since you don't want the containers updated automatically.
In that case, `watchtower_containers_updated` is exactly what you are requesting, although the name is a bit misleading of course. It's the number of containers that *would* have been updated if not updating was turned off.

The number of checked containers is `watchtower_containers_scanned` if that's what you meant.
